### PR TITLE
Implement custom allocator for Ice Box engine.

### LINKED ISSUE #4: Create Custom Allocator
Create a custom allocator for IceBox.

Deliverables:
* Slab allocator for small data types (up to 512 bytes - arbitrary)
* Buddy allocator for larger data types (maybe - depends what we consider to be most effective here)
* Memory maps for huge allocations (1GB+)

### LINKED ISSUE #20: Document Custom Allocator
**Is your feature request related to a problem? Please describe.**
Custom allocator currently lacks documentation on usage.

**Describe the solution you'd like**
Add documentation to the allocator header.

### PR DESCRIPTION
**Pull request by AlexSabourinDev**
Fixes #4 and fixes #20 .

See #4 for documentation on the implementation or IBAllocator.cpp.

### CODE REVIEW

**Comment by skaarjslayer** [comment]
Will probably be best to provide documentation on allocator usage. This can done as part of a separate issue from this one.

**Comment by AlexSabourinDev** [comment]
Smart, I hadn't considered documentation on usage

**Comment by skaarjslayer** [comment]
Yea mostly just because I'm not sure myself when I would or would not use the various different allocators

**Comment by AlexSabourinDev** [comment]
Added documentation on usage. Fixes #20

**Pull request merged**
